spring.application.name: propiedades
server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${DATA_BASE_URL:jdbc:postgresql://db-postgresql-nyc3-43635-do-user-15381753-0.c.db.ondigitalocean.com:25060/nurairbnbc}
    username: ${DATA_BASE_USERNAME:doadmin}
    password: ${DATA_BASE_PASSWORD:AVNS_x7KsU5lHHREJnxnI2cd}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: '*'

